### ISSUE TITLE
发起活动表单的字段微调

### ISSUE THREAD

**Issue by Alive24** [AgoraAcademy/ProjectAgora-mobile#10]
1. 活动简介较长时应该能往下挤
2. 活动开始时间和活动结束时间简写成开始时间和结束时间，避免换行
3. 活动过期时间改成截止时间，意思是指截止报名时间（有些活动需要提前结束报名而不是开始之后才结束报名）
4.活动费用和截止时间都应该是附加选项，不是必填

**Comment by Binaryify** [comment]
修改活动出现无法更新的情况
